### ISSUE TITLE
Error in GuardFile.php: failed to open stream

### ISSUE THREAD

**Issue by skizzo** [potsky/microsoft-translator-php-sdk#1]
Hi, I get the error

`File '/home/.sites/878/site2307301/web/api/3.0/vendor/potsky/microsoft-translator-php-sdk/src/MicrosoftTranslator/GuardFile.php', line #268: file_get_contents(/home/.sites/878/site2307301/tmp/microsoft-translator-at-e585666bda4358c98f0ff767af763fdfb2c2b4f2): failed to open stream`

What am I doing wrong?

**Comment by potsky** [comment]
Hi,

nothing, you're almost right! Is the `/home/.sites/878/site2307301/tmp/` directory writable by the web server user ?

Is there some files in the `tmp` directory ?

**Comment by potsky** [comment]
> I store access tokens in this directory for future API calls.

**Comment by skizzo** [comment]
Thanks, I think it's because I use SLIM 3 for my REST API which has the line
`RewriteBase /api/3.0/`
in the .htaccess. Because if I get the value from `getcwd()`in the file I want to use your translator (index.php, in same folder as the mentioned .htaccess), its value is `/home/.sites/878/site2307301/web/api/3.0`.. Any ideas?

**Comment by skizzo** [comment]
Okay, seems to be a .htaccess problem after all, but even when using it outside of a REST API, I still get the error

`Error #0 with message : Unable to generate a new access token : {"http_code":400,"http_body":"{\"error\":\"invalid_client\",\"error_description\":\"ACS50012: Authentication failed.\\r\\nTrace ID: bf196400-c65f-4a6c-afc0-9fa721beec3f\\r\\nCorrelation ID: 0ff830c5-0fba-4bfe-91de-478d9eb266b1\\r\\nTimestamp: 2016-05-20 17:13:10Z\"}","duration":602}`

Could it be because my Azure account and app have both just been created an hour ago and it takes a while..? Thanks

**Comment by potsky** [comment]
Ok, I don't really like SLIM because of this kind of problems. I really prefer Lumen for example.

Anyway:
1. You can set the option `guard_file_dir_path` when instantiating the client and set a temporary directory.  You will no more have problem with the Access token directory.
2. According to the error message, it seems your credentials are not correct. Have you created a client on the Microsoft web site ?

**Comment by skizzo** [comment]
Thanks for your reply. What's the purpose of the Redirect URI I have to enter when registering a new application? Maybe that's the problem.. 
![screen shot 2016-05-21 at 12 48 50](https://cloud.githubusercontent.com/assets/2892572/15447957/7d2b9194-1f52-11e6-8a6c-3040788926e4.png)

**Comment by skizzo** [comment]
Okay, setting the `guard_file_dir_path` worked for me! Also, I had to create a new app in which the client ID doesnt contain any non-alphanumeric characters (the switch from "`test_name`" to "`testname`" removed the authentication error. Weird, but it worked!
You can close this issue if you want, thanks for your help and this pretty awesome tool! 👍

**Comment by potsky** [comment]
Nice!
